/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainWindow.java
 *
 * Created on 01/11/2010, 00:24:13
 */
package gui;

import mouselisteners.DrawObjectsListener;
import mouselisteners.DrawPointsListener;
import util.ObjectsControl;
import util.VisibilityGraph;
import javax.swing.JOptionPane;

/**
 *
 * @author Lucas
 */
public class MainWindow extends javax.swing.JFrame {

    /** Creates new form MainWindow */
    ObjectsControl objectsControl = new ObjectsControl();
    DrawObjectsListener drawObjectListenter = new DrawObjectsListener();
    DrawPointsListener drawPoints = new DrawPointsListener();
    VisibilityGraph visibilityGraph;
    boolean expandido = false;
    int tamanhoEixo;
//    Grafo grafo;

    

    public MainWindow() {

        initComponents();

        objectsControl.setWorld(world);
        drawObjectListenter.setObjectsControl(objectsControl);
        drawPoints.setObjectsControl(objectsControl);
        world.setObjectsControl(objectsControl);

         visibilityGraph = new VisibilityGraph(objectsControl);
         world.setVisibilityGraph(visibilityGraph);
         addObjectsButton.setEnabled(false);
         enlargeObjects.setEnabled(false);
         generatePathbutton.setEnabled(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addObjectsButton = new javax.swing.JToggleButton();
        enlargeObjects = new javax.swing.JButton();
        generatePathbutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        world = new gui.World();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Grafo de Visibilidade");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        addObjectsButton.setText("Adicionar obstáculos");
        addObjectsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addObjectsButtonActionPerformed(evt);
            }
        });

        enlargeObjects.setText("Expandir obstáculos");
        enlargeObjects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enlargeObjectsActionPerformed(evt);
            }
        });

        generatePathbutton.setText("Gerar caminho");
        generatePathbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatePathbuttonActionPerformed(evt);
            }
        });

        jLabel1.setText("Eixo do robo (cm)");

        jButton1.setText("Configurar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addObjectsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enlargeObjects)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generatePathbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(addObjectsButton)
                    .addComponent(enlargeObjects)
                    .addComponent(generatePathbutton))
                .addContainerGap())
        );

        javax.swing.GroupLayout worldLayout = new javax.swing.GroupLayout(world);
        world.setLayout(worldLayout);
        worldLayout.setHorizontalGroup(
            worldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );
        worldLayout.setVerticalGroup(
            worldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(world, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(world, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addObjectsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addObjectsButtonActionPerformed
        if (addObjectsButton.isSelected()) {
            world.addMouseListener(drawObjectListenter);
            world.addMouseMotionListener(drawObjectListenter);
        }else{
            addObjectsButton.setEnabled(false);
            enlargeObjects.setEnabled(true);
            generatePathbutton.setEnabled(false);
            world.removeMouseListener(drawObjectListenter);
            world.removeMouseMotionListener(drawObjectListenter);
        }
    }//GEN-LAST:event_addObjectsButtonActionPerformed

    private void enlargeObjectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enlargeObjectsActionPerformed
        if(!expandido){
            objectsControl.expandObjects(tamanhoEixo);
            generatePathbutton.setEnabled(true);
        }
        world.repaint();
        JOptionPane.showMessageDialog(null, "Botão esquerdo posiciona o Inicio; Botão direito posiciona o Fim");
        world.addMouseListener(drawPoints);
        world.addMouseMotionListener(drawPoints);
        expandido = true;
    }//GEN-LAST:event_enlargeObjectsActionPerformed

    private void generatePathbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatePathbuttonActionPerformed
        objectsControl.createListOfExtendedPoints();
        visibilityGraph.createGraph();
        this.repaint();
        enlargeObjects.setEnabled(false);
    }//GEN-LAST:event_generatePathbuttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        tamanhoEixo = Integer.parseInt(jTextField1.getText());
        jLabel1.setEnabled(false);
        jButton1.setEnabled(false);
        jTextField1.setEnabled(false);
        addObjectsButton.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton addObjectsButton;
    private javax.swing.JButton enlargeObjects;
    private javax.swing.JButton generatePathbutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private gui.World world;
    // End of variables declaration//GEN-END:variables
}
